jingboApp
.config(function($stateProvider,$urlRouterProvider){
	$stateProvider
	.state('index',{
		url:'/main',
		abstract:true,
		templateUrl:'index.html',
		controller:'indexCtrl'
	}).state('ranges',{
		url:"/ranges",
		templateUrl:'templates/ranges.html',
		controller:'rangesCtrl'
	}).state('cranes',{
		url:"/cranes",
		templateUrl:'templates/cranes.html',
		controller:'cranesCtrl'
	})
	.state('cranes-1',{
		url:"/cranes-1",
		templateUrl:'templates/cranes-1.html',
		controller:'cranes1Ctrl'
	})
	.state('cranes-2',{
		url:"/cranes-2",
		templateUrl:'templates/cranes-2.html',
		controller:'cranes2Ctrl'
	})
	.state('status',{
		url:"/status",
		templateUrl:'templates/status.html',
		controller:'statusCtrl'
	})
	.state('track',{
		url:"/track",
		templateUrl:'templates/track.html',
		controller:'trackCtrl'
	})
	.state('import',{
		url:"/import",
		templateUrl:'templates/import.html',
		controller:'importCtrl'
	})
	.state('import-1',{
		url:"/import-1",
		templateUrl:'templates/import-1.html',
		controller:'import-1Ctrl'
	})
	.state('input',{
		url:"/input",
		templateUrl:'templates/input.html',
		controller:'inputCtrl'
	})
	.state('input-1',{
		url:"/input-1",
		templateUrl:'templates/input-1.html',
		controller:'input-1Ctrl'
	})
	.state('orders',{
		url:"/orders",
		templateUrl:'templates/orders.html',
		controller:'ordersCtrl'
	})
	.state('orders-1',{
		url:"/orders-1",
		templateUrl:'templates/orders-1.html',
		controller:'orders-1Ctrl'
	})
	.state('home',{
		url:"/home",
		// abstract:true,
		templateUrl:'templates/home.html',
		controller:'homeCtrl'
	});
	$urlRouterProvider.otherwise('/home');
})